package com.nexpath.enums;

public enum CreditTransactionType {
    SIGNUP_BONUS,
    PURCHASE,
    REFERRAL,
    EARNED_DAILY,
    SPENT_ROADMAP,
    SPENT_SKILLGAP,
    SPENT_RESUME,
    SPENT_CHAT,
    CONNECTION_LOCKED,
    CONNECTION_DEDUCTED,
    CONNECTION_REFUNDED,
    HIRE_REWARD,
    BOOST_POST,
    REFUND
}
